// <auto-generated />
using System;
using EncurtadorUrl.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EncurtadorUrl.Data.Migrations
{
    [DbContext(typeof(EncurtadorUrlDbContext))]
    partial class EncurtadorUrlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("EncurtadorUrl.Data.Model.Url", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataExpiracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("urlEncurtada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("urlOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
